#!/bin/zsh

# Set language to US English UTF-8.
export LANG=en_US.UTF-8

# Enable completion menu reversing.
bindkey '^[[Z' reverse-menu-complete

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt inc_append_history
setopt share_history

# Determine OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

[ -f /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"

# Set default project path
export PROJECT_PATH="$HOME/Projects"

# Append PATH
export PATH=$HOME/.mix/escripts:$GOPATH/bin:$HOME/.local/bin:$HOME/bin:$HOME/.cargo/bin:/usr/sbin:/usr/local/bin:$PATH

# Set key timeouet to 1 for vi mode
export KEYTIMEOUT=1

# Default editor ist nvim
export EDITOR="nvim"

# Only alias open on linux
if [[ $machine == Linux ]]; then
    alias open='xdg-open'
fi

# Use gpg-agent for instead of the default ssh-agent
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye > /dev/null

typeset -aU path

# Setup FZF
eval "$(fzf --zsh)"

# Configure FZF to use Ripgrep
export FZF_DEFAULT_COMMAND='rg --files --hidden'

# Initialize SDKMan
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# Taken from https://koenwoortman.com/zsh-split-zshrc-into-multiple-files/
for conf in "$HOME/.config/zsh/conf.d/"*.zsh; do
    source "${conf}"
done
unset conf


### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/rsmidt/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

# pnpm
export PNPM_HOME="/Users/rsmidt/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/Users/rsmidt/.bun/_bun" ] && source "/Users/rsmidt/.bun/_bun"

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/rsmidt/.dart-cli-completion/zsh-config.zsh ]] && . /Users/rsmidt/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]

# mise (Manages Erlang & Elixir)
eval "$(mise activate zsh)"
